### ISSUE TITLE
Your congress-legislators source is not up to date

### ISSUE THREAD

**Issue by nerdtypething** [Geocodio/docs#12]
I did a test GET against an address in AL and noticed that the data for senators didn't reflect Doug Jones' recent election to the Senate. In the response it says you are sourcing from https://github.com/unitedstates/. Looks like you need to run the scraping scripts more frequently than you already do.

**Comment by MiniCodeMonkey** [comment]
I apologize for not seeing this until now, it was resolved earlier in the year.
