### ISSUE TITLE
typo in the Fields section of the docs (Node)

### ISSUE THREAD

**Issue by thellllvirtuoso** [Geocodio/docs#18]
On the right side where the code is posted, it says:

const geocodio = new Geocodio('YOUR_API_KEY');

when it should say

const geocoder = new Geocodio('YOUR_API_KEY');

**Comment by MiniCodeMonkey** [comment]
Hi @thellllvirtuoso! Thanks for reporting this.

I can't seem to reproduce the issue, browsing through the documentation.

It looks like we consistently use this construct:
```
const Geocodio = require('geocodio-library-node');
const geocoder = new Geocodio('YOUR_API_KEY');
```

<img width="510" alt="Screen Shot 2022-10-11 at 09 06 27" src="https://user-images.githubusercontent.com/220535/195019493-3323ba7e-1232-46e7-a717-4b1f9258f8ac.png">


Can you clarify in which section you saw this issue?
