### ISSUE TITLE
Fields Typo in Ruby Library Documentation

### ISSUE THREAD

**Issue by GoldenPavilion** [Geocodio/docs#19]
When implementing Geocodio integration and passing in parameters to `.geocode()`, the `:fields` parameter leads to a NameError. 

```
NameError in ApiCallsController#call_geocodio
undefined local variable or method `w' for #<ApiCallsController:0x00000000025328> 
```
I believe this is a typo and that it should be the `fields:` parameter instead. 

For example:

`location = geocodio.geocode(['1109 N Highland St, Arlington VA'], :fields %w[census2010 census])`

Should be:

`location = geocodio.geocode(['1109 N Highland St, Arlington VA'], fields: %w[census2010 census])`

This will likely need to be updated for each of the available appended fields.

**Comment by MiniCodeMonkey** [comment]
This was resolved here: https://github.com/Geocodio/docs/commit/2fc85963848267efc9a8a3e3212bec6c0c91cd42
