### ISSUE TITLE
500 internal server error when pulling more than 200 records

### ISSUE THREAD

**Issue by codebreakergh** [Geocodio/docs#6]
<b>Fatal error</b>:  Uncaught exception 'Guzzle\Http\Exception\ServerErrorResponseException' with message 'Server error response
[status code] 500
[reason phrase] Internal Server Error
[url] http://api.geocod.io/v1/geocode?q=KM%2B19.5%2BCarretera%2BEsc%C3%A9nica%2BTijuana%2B-%2BEnsenada%2B%2BRosarito%2BCA&amp;api_key=3ef118e616ce38de613a5171c8556de4166eccc' in D:\xampp\htdocs\ph-rets\vendor\guzzle\http\Guzzle\Http\Exception\BadResponseException.php:43
Stack trace:
#0 D:\xampp\htdocs\ph-rets\vendor\guzzle\http\Guzzle\Http\Message\Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\Request), Object(Guzzle\Http\Message\Response))
#1 [internal function]: Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 D:\xampp\htdocs\ph-rets\vendor\symfony\event-dispatcher\EventDispatcher.php(158): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher in <b>D:\xampp\htdocs\ph-rets\vendor\guzzle\http\Guzzle\Http\Exception\BadResponseException.php</b> on line <b>43</b><br />

**Comment by MiniCodeMonkey** [comment]
Hi there,

The issue should have been resolved now. Please let me know if you can reproduce.

Mathias
